version: '3.8'

services:
  filecodebox:
    image: lanol/filecodebox:beta
    container_name: filecodebox
    restart: always
    ports:
      - "12345:12345"
    volumes:
      - /home/soulnail/FileCodeBox/app/data:/app/data 
